USE [master]
GO

/****** Object:  Database [Video Game Database]    Script Date: 11/14/2013 8:29:09 AM ******/
CREATE DATABASE [Video Game Database]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Video Game Database', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\Video Game Database.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Video Game Database_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\Video Game Database_log.ldf' , SIZE = 24384KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Video Game Database] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Video Game Database].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Video Game Database] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Video Game Database] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Video Game Database] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Video Game Database] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Video Game Database] SET ARITHABORT OFF 
GO

ALTER DATABASE [Video Game Database] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Video Game Database] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Video Game Database] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Video Game Database] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Video Game Database] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Video Game Database] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Video Game Database] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Video Game Database] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Video Game Database] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Video Game Database] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Video Game Database] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Video Game Database] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Video Game Database] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Video Game Database] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Video Game Database] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Video Game Database] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Video Game Database] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Video Game Database] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Video Game Database] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Video Game Database] SET  MULTI_USER 
GO

ALTER DATABASE [Video Game Database] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Video Game Database] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Video Game Database] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Video Game Database] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Video Game Database] SET  READ_WRITE 
GO


